apiVersion: argoproj.io/v1alpha1 # ArgoCD Application resource
kind: Application               # Kind of resource
metadata:                        # Metadata section                         
  name: python-application          # App name
  namespace: argocd             # Must exist in ArgoCD namespace
spec:
  project: python-team        # Assigns app to the frontend-team Project
  source:
    repoURL: https://github.com/hanamanttaranal-cpu/python-fullstack-e-commerce-argocd.git  # Git repo
    targetRevision: main        # Branch to watch
    path: kubernetes     # Path in repo with manifests
  destination:
    server: https://kubernetes.default.svc   # Target cluster, run `argocd cluster list` to see
    namespace: argocd          # Namespace inside that cluster
  syncPolicy:                    # Sync policy settings
    automated:                   # Enable automated sync
      prune: true                 # Delete resources removed from Git
      selfHeal: true              # Correct drift if resources change in cluster
    syncOptions:                 # Additional sync options
      - CreateNamespace=true   