apiVersion: apps/v1
kind: Deployment
metadata:
  name: auramarket-backend-deployment
  labels:
    app: auramarket-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auramarket-backend
  template:
    metadata:
      labels:
        app: auramarket-backend
    spec:
      containers:
      - name: auramarket-backend
        image: auramarket-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: auramarket-backend-service
  labels:
    app: auramarket-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: auramarket-backend
