apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: auru
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:mysql://YOUR-RDS-ENDPOINT:3306/mydatabase?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "password123"

  STRIPE_API_KEY: "sk_test_51xxxxxxxxxxxxxxxxxxxxxxxx"

  CLOUDINARY_CLOUD_NAME: "demo-cloud"
  CLOUDINARY_API_KEY: "123456789012345"
  CLOUDINARY_API_SECRET: "abcdef123456789xyz"
