apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: auru
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 542119827827.dkr.ecr.ap-south-2.amazonaws.com/frontend-java:latest
        ports:
        - containerPort: 80
